version: 2

jobs:
    build:
        docker:
            - image: circleci/node:9.11.2
        working_directory: ~/jbtips
        steps:
            - add_ssh_keys:
                fingerprints:
                    - "a8:d7:92:82:90:5f:d2:2b:53:f8:10:72:37:01:08:3c"
            - checkout
            - run:
                name: Install Hugo
                command: wget https://github.com/gohugoio/hugo/releases/download/v0.42.1/hugo_0.42.1_Linux-64bit.deb -O /tmp/hugo.deb && sudo dpkg -i /tmp/hugo.deb
            - run:
                name: Install deployment dependencies
                command: sudo apt install rsync
            - deploy:
                name: Deploy to Github Pages
                command: chmod +x ./.circleci/deploy.sh
            - deploy:
                name: Deploy to Github Pages
                command: ./.circleci/deploy.sh
